apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "simulators.fullname" . }}
  labels:
    app: {{ template "simulators.name" . }}
    chart: {{ template "simulators.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "simulators.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "simulators.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8444
              protocol: TCP
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
              scheme: {{ .Values.readinessProbe.httpGet.scheme }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
              scheme: {{ .Values.livenessProbe.httpGet.scheme }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          {{- end }}
          env:
            - name: SWITCH_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "simulators.fullname" . }}
                  key: SWITCH_ENDPOINT
            - name: PARTIES_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "simulators.fullname" . }}
                  key: PARTIES_ENDPOINT
            - name: QUOTES_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "simulators.fullname" . }}
                  key: QUOTES_ENDPOINT
            - name: TRANSFERS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "simulators.fullname" . }}
                  key: TRANSFERS_ENDPOINT
            - name: BEARER_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: {{ template "simulators.fullname" . }}
                  key: BEARER_TOKEN
          resources:
      imagePullSecrets:
        - name: regcred
{{ toYaml .Values.resources | indent 12 }}
        - name: {{ .Values.imageCredentials.name }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}